; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
build_flags = 
  -DUSE_TINYUSB 
  -DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC
  -DPICO_STDIO_USB_ENABLE_RESET_VIA_BAUD_RATE=1
  -DPICO_STDIO_USB_ENABLE_RESET_VIA_VENDOR_INTERFACE=1
upload_protocol = picotool
upload_flags = -f

; Set these to the actual modem device once it appears
; upload_port = /dev/cu.usbmodemXXXX
; monitor_port = /dev/cu.usbmodemXXXX
monitor_speed = 115200

custom_prog_version = 0.1


lib_deps =
 adafruit/Adafruit TinyUSB Library@^3.3.3
 adafruit/Adafruit NeoPixel
